const randomTexts = [
  "Hello bhai 👋",
  "Kya haal chaal hai?",
  "Live chat chal raha hai 🔴",
  "React Redux seekh raha hoon",
  "Frontend developer banne ka sapna",
  "JavaScript mast language hai",
  "Aaj bug fix ho gaya 😄",
  "Coding thodi tough hai par fun hai",
  "Practice makes perfect 💪",
  "Daily code karna zaroori hai",
  "Redux Toolkit easy lag raha hai",
  "Component re-render ho raha hai",
  "useEffect samajh aa gaya",
  "CORS error ne pareshan kar diya 😤",
  "Finally proxy se kaam ho gaya ✅",
  "YouTube clone bana raha hoon",
  "Live stream feature add kar raha hoon",
  "Tailwind CSS fast hai ⚡",
  "VS Code bina zindagi adhuri hai",
  "Debugger best friend hai 🐞",
  "Interview ke liye prepare kar raha hoon",
  "DSA bhi start karna padega",
  "JavaScript closures samajh aaye",
  "Async await easy ho gaya",
  "API se data aa raha hai 🔥",
  "Loading spinner lagana baaki hai",
  "Error handling zaroori hai",
  "Clean UI banana hai",
  "Production build ready hai 🚀",
  "GitHub par code push kar diya",
  "Pull request create ho gaya",
  "Code review pending hai",
  "Performance optimize karna hai",
  "Memoization samajh aa rahi hai",
  "Selectors ko optimize kar diya",
  "Live chat smooth chal raha hai",
  "Ab confidence aa raha hai 😎",
  "Job ke liye apply kar raha hoon",
  "First salary ka wait hai 💰",
  "Never give up 💯",
  "Code daily, grow daily 🌱"
];

const randomNames = [
  "Mayank",
  "Aman",
  "Rohit",
  "Rahul",
  "Amit",
  "Sachin",
  "Saurabh",
  "Vikas",
  "Ankit",
  "Deepak",
  "Kunal",
  "Nitin",
  "Pankaj",
  "Manish",
  "Harsh",
  "Arjun",
  "Aditya",
  "Shubham",
  "Prakash",
  "Vivek",
  "Neeraj",
  "Sandeep",
  "Yash",
  "Mohit",
  "Ravi",
  "Sunil",
  "Akash",
  "Abhishek",
  "Gaurav",
  "Kapil",
  "Tarun",
  "Naveen",
  "Lokesh",
  "Raj",
  "Vijay",
  "Siddharth",
  "Karan",
  "Dev",
  "Nikhil",
  "Varun",
  "Ajay",
  "Sanjay",
  "Rakesh",
  "Umesh",
  "Bhavesh"
];

export function generateRandomText ()  {
    return  randomTexts[Math.floor(Math.random() * randomTexts.length)];
    
}

export function  generateRandomName () {
    return randomNames[Math.floor(Math.random() * randomNames.length)]
}